# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c0b8e140f877d8ab37bc961532363c841725dc3b12c5071f6719c52c1a7c14dab8ebe47d9dc2897135b8326e73f63a73a8037249214ac83c55eafac611e75f8

test:
  secret_key_base: eafd926aafdd9f5ef6facd79c5df03c8040eb231fa07fb358a912711852068971258c09b204c7633903d58faa0b38383d564b066e4c92deac74dce192ee5b494

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
